apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: 010647576202.dkr.ecr.us-east-1.amazonaws.com/my-ecr-repo:latest
          ports:
            - containerPort: 5000
