AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal Amazon EKS Cluster with a Single Node (Default VPC)

Resources:
  EKSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: my-eks-cluster
      RoleArn:
        Fn::GetAtt:
          - EKSRole
          - Arn
      Version: '1.21'

  NodeInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Fn::Ref: EKSNodeRole

  EKSNodeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

  NodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName:
        Fn::GetAtt:
          - EKSCluster
          - Name
      NodegroupName: my-node-group
      NodeRole:
        Fn::GetAtt:
          - EKSNodeRole
          - Arn
      ScalingConfig:
        MinSize: 1
        MaxSize: 1
        DesiredSize: 1
